export const COLORS = [
  "#6CD0FC",
  "#A78BFA",
  "#F4AEFF",
  "#F88171",
  "#FBA966",
  "#87DFA7",
  "#60A5FA",
  "#C084FC",
  "#FFDB21",
  "#FF7E96",
  "#E4F425",
  "#C5BBFF",
  "#7ED5C5",
  "#D1D1D1",
  "#F88171",
  "#5FB4C7",
  "#9CA5FF",
  "#DE8E6B",
  "#F472B6",
  "#B3E7F2",
  "#FF9921",
  "#BAEB7B",
  "#9C9C9C",
  "#C084FC",
  "#E3C575",
  "#FFAEC2",
  "#AFC0D2",
];
export const columns = [
  {
    title: "#",
    dataIndex: "index",
    key: "index",
  },
  {
    title: "install ID",
    dataIndex: "install_id",
    key: "install_id",
  },
  {
    title: "date",
    dataIndex: "start_date",
    key: "start_date",
  },
  {
    title: "build",
    dataIndex: "build",
    key: "build",
  },
  {
    title: "branch",
    dataIndex: "branch",
    key: "branch",
  },
  {
    title: "status",
    dataIndex: "last_event",
    key: "status",
  },
  {
    title: "time",
    dataIndex: "download_time",
    key: "download_time",
  },
  // {
  //   title: "delivery link",
  //   dataIndex: "delivery_link",
  //   key: "delivery_link",
  // },
];
